CREATE DATABASE MEU_PESQUEIRO_DB;
USE MEU_PESQUEIRO_DB;

-- TABELA: FUNCIONÁRIOS
CREATE TABLE TBL_FUNCIONARIOS (
    ID_FUNCIONARIO INT PRIMARY KEY,
    NOME_FUNCIONARIO VARCHAR(100),
    SENHA_FUNCIONARIO VARCHAR(30)
);

-- TABELA: EQUIPAMENTOS
CREATE TABLE TBL_EQUIPAMENTOS (
    ID_EQUIPAMENTOS INT PRIMARY KEY,
    NOME_EQUIPAMENTO VARCHAR(100),
    EQUIPAMENTO_EM_USO BIT,
    QUANTIDADE_EQUIPAMENTO INT
);

-- TABELA: GERENCIA (Relacionamento N:N entre FUNCIONÁRIOS e EQUIPAMENTOS)
CREATE TABLE TBL_GERENCIA (
    ID_FUNCIONARIO INT,
    ID_EQUIPAMENTOS INT,
    PRIMARY KEY (ID_FUNCIONARIO, ID_EQUIPAMENTOS),
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES TBL_FUNCIONARIOS(ID_FUNCIONARIO),
    FOREIGN KEY (ID_EQUIPAMENTOS) REFERENCES TBL_EQUIPAMENTOS(ID_EQUIPAMENTOS)
);

-- TABELA: ALUGUEL
CREATE TABLE TBL_ALUGUEL (
    ID_ALUGUEL INT PRIMARY KEY,
    VALOR_ALUGUEL DECIMAL(10,2),
    DATA_HORA_RETIRADA DATETIME,
    DATA_HORA_DEVOLUCAO DATETIME,
    OBSERVACAO VARCHAR(500),
    ID_EQUIPAMENTOS INT,
    FOREIGN KEY (ID_EQUIPAMENTOS) REFERENCES TBL_EQUIPAMENTOS(ID_EQUIPAMENTOS)
);

-- TABELA: CLIENTE
CREATE TABLE TBL_CLIENTE (
    ID_CLIENTE INT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(100),
    SENHA_CLIENTE VARCHAR(30),
    EMAIL_CLIENTE VARCHAR(40)
);

-- TABELA: ALUGUEL_CLIENTE (Relacionamento N:N)
CREATE TABLE TBL_ALUGUEL_CLIENTE (
    ID_CLIENTE INT,
    ID_ALUGUEL INT,
    PRIMARY KEY (ID_CLIENTE, ID_ALUGUEL),
    FOREIGN KEY (ID_CLIENTE) REFERENCES TBL_CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_ALUGUEL) REFERENCES TBL_ALUGUEL(ID_ALUGUEL)
);

-- TABELA: COMPRA
CREATE TABLE TBL_COMPRA (
    ID_COMPRA INT PRIMARY KEY,
    DT_COMPRA DATE,
    VALOR_TOTAL DECIMAL(10,2)
);

-- TABELA: COMPRA_CLIENTE (Relacionamento N:N)
CREATE TABLE TBL_COMPRA_CLIENTE (
    ID_CLIENTE INT,
    ID_COMPRA INT,
    PRIMARY KEY (ID_CLIENTE, ID_COMPRA),
    FOREIGN KEY (ID_CLIENTE) REFERENCES TBL_CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_COMPRA) REFERENCES TBL_COMPRA(ID_COMPRA)
);

-- TABELA: PRODUTOS
CREATE TABLE TBL_PRODUTOS (
    ID_PRODUTO INT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(100),
    VALOR_PRODUTO DECIMAL(10,2),
    QTD_PRODUTO INT,
    FORNECEDOR VARCHAR(100),
    ID_COMPRA INT,
    FOREIGN KEY (ID_COMPRA) REFERENCES TBL_COMPRA(ID_COMPRA)
);

-- TABELA: ESPECIE
CREATE TABLE TBL_ESPECIE (
    ID_ESPECIE INT PRIMARY KEY,
    NOME_ESPECIE VARCHAR(100),
    VALOR_ESPECIE DECIMAL(10,2),
    FORNECEDOR_ESPECIE VARCHAR(100)
);

-- TABELA: PEIXE_CAPTURADO
CREATE TABLE TBL_PEIXE_CAPTURADO (
    ID_PEIXE_CAPTURADO INT PRIMARY KEY,
    PESO DECIMAL(5,2),
    DATA_PEIXE_CAPTURADO DATE,
    ID_ESPECIE INT,
    FOREIGN KEY (ID_ESPECIE) REFERENCES TBL_ESPECIE(ID_ESPECIE)
);

-- TABELA: PEIXE_CLIENTE (Relacionamento N:N)
CREATE TABLE TBL_PEIXE_CLIENTE (
    ID_CLIENTE INT,
    ID_PEIXE_CAPTURADO INT,
    PRIMARY KEY (ID_CLIENTE, ID_PEIXE_CAPTURADO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES TBL_CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_PEIXE_CAPTURADO) REFERENCES TBL_PEIXE_CAPTURADO(ID_PEIXE_CAPTURADO)
);

-- TABELA: LAGOS
CREATE TABLE TBL_LAGOS (
    ID_LAGO INT PRIMARY KEY,
    NOME_LAGO VARCHAR(100)
);

-- TABELA: ESPECIE_LAGO (Relacionamento N:N)
CREATE TABLE TBL_ESPECIE_LAGO (
    ID_ESPECIE INT,
    ID_LAGO INT,
    QTD_PEIXES INT,
    PRIMARY KEY (ID_ESPECIE, ID_LAGO),
    FOREIGN KEY (ID_ESPECIE) REFERENCES TBL_ESPECIE(ID_ESPECIE),
    FOREIGN KEY (ID_LAGO) REFERENCES TBL_LAGOS(ID_LAGO)
);

-- TABELA: PESQUEIRO
CREATE TABLE TBL_PESQUEIRO (
    ID_PESQUEIRO INT PRIMARY KEY,
    NOME VARCHAR(100),
    EMAIL VARCHAR(100),
    TELEFONE VARCHAR(20),
    LATITUDE VARCHAR(50),
    LONGITUDE VARCHAR(50),
    FOTOS TEXT
);

-- TABELA: COMENTARIOS
CREATE TABLE TBL_COMENTARIOS (
    ID_COMENTARIO INT PRIMARY KEY,
    TEXTO VARCHAR(500),
    AVALIACAO INT,
    ID_PESQUEIRO INT,
    FOREIGN KEY (ID_PESQUEIRO) REFERENCES TBL_PESQUEIRO(ID_PESQUEIRO)
);

-- TABELA: CLIENTE_COMENTARIO (Relacionamento N:N)
CREATE TABLE TBL_CLIENTE_COMENTARIO (
    ID_COMENTARIO INT,
    ID_CLIENTE INT,
    PRIMARY KEY (ID_COMENTARIO, ID_CLIENTE),
    FOREIGN KEY (ID_COMENTARIO) REFERENCES TBL_COMENTARIOS(ID_COMENTARIO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES TBL_CLIENTE(ID_CLIENTE)
);

-- TABELA: FAVORITOS (Relacionamento N:N)
CREATE TABLE TBL_FAVORITOS (
    ID_PESQUEIRO INT,
    ID_CLIENTE INT,
    PRIMARY KEY (ID_PESQUEIRO, ID_CLIENTE),
    FOREIGN KEY (ID_PESQUEIRO) REFERENCES TBL_PESQUEIRO(ID_PESQUEIRO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES TBL_CLIENTE(ID_CLIENTE)
);
